name: wms_mobile

services:
  build-apk:
    build:
      context: .
      args:
        BUILD_MODE: ${BUILD_MODE:-release}
    image: wms_mobile_apk
    container_name: wms_mobile_apk
    volumes:
      - ./apk_out:/output
    restart: "no"
